version: '3.6'
services:
  goservice-1:
    image: goservice-1:3.0.0
    build: '.'
    environment:
      - SERVER_NAME=goservice-1
    ports:
      - '8081:8080'
    networks:
      - 'app-network'
  goservice-2:
    image: goservice-2:2.0.0
    build: '.'
    ports:
      - '8082:8080'
    environment:
      - SERVER_NAME=goservice-2
    networks:
      - 'app-network'

  nginx:
    build: './nginx'
    ports:
      - '80:80'
    depends_on:
      - 'goservice-1'
      - 'goservice-2'
    networks:
      - 'app-network'
networks:
  app-network:
    driver: bridge
